### ISSUE TITLE
Problem with whitespaces, quotes in query String - Illegal character in query 

### ISSUE THREAD

**Issue by jtolkanowicz** [afedulov/google-web-search#1]
If you have 'special' character in query String you will get 
**java.lang.IllegalArgumentException: Illegal character in query** . 
For example
"bunnies\":
"bunnies from"
etc
Maybe you should use URLEncoder before executing query?
Stacktrace:
```
java.lang.IllegalArgumentException: Illegal character in query at index 39: https://www.google.com/search?q=bunnies"&num=10&as_sitesearch=stackoverflow.com

	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at com.afedulov.search.GoogleWebSearch.getResponse(GoogleWebSearch.java:61)
	at com.afedulov.search.GoogleWebSearch.search(GoogleWebSearch.java:41)
	at com.afedulov.search.GoogleWebSearchTest.shouldSearch(GoogleWebSearchTest.java:37)
```
Enviroment:
Ubuntu 16.04
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)

**Comment by afedulov** [comment]
Thanks for reporting. Fixed in 32a29963906fe94ab3fdd12f61b4c1e2dcddd9ae .
